### ISSUE TITLE
Can I use existing VPC and subnets for this solution?

### ISSUE THREAD

**Issue by rmandadapu** [aws-samples/aws-golden-ami-pipeline-sample#3]
I'm unable to select my existing vpc and subnets while deploying this template.

**Comment by kwwaikar** [comment]
Hi @rmandadapu,

The default sample configuration provided creates a VPC, subnet(s) and uses the same for golden AMI creation/continuous assessment process. Yes, You can modify the template to refer to your existing VPC and subnets.

**Comment by kwwaikar** [comment]
closing issue

**Comment by rmandadapu** [comment]
Sure, Will take a look, Since it is huge and I'm new to cloud formation, I'm expecting some help.
