### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by dtd379** [aws-samples/aws-golden-ami-pipeline-sample#4]
I've encountered an error with the CopyAndShareAMI doc: 

> Could not parse request body into json: Unexpected character ('u' (code 117)): was expecting comma to separate Object entries
>  at [Source: [B@8969445; line: 1, column: 34] (Service: AWSLambda; Status Code: 400; Error Code: InvalidRequestContentException; Request ID: 2cf1fd24-9006-11e8-b6d5-7b2d50c24109)

The parameter I'm passing is:
`MetadataJSON={1234567890:"us-east-1,us-east-2"}`

The full input payload is:
`"{\"MetadataJSON\":\"{1234567890:\"us-east-1,us-east-2\"}\",\"ProductName\":\"dev-0.1\",\"ProductOSAndVersion\":\"AMLinux-0.1\",\"version\":\"1\",\"AmiIDParamName\":\"/GoldenAMI/AMLinux-0.1/dev-0.1/1\", \"MetadataParamName\":\"/GoldenAMI/AMLinux-0.1/dev-0.1/1/temp\"}"`

**Comment by sai4cloud** [comment]
SSm document metadatajson 

MetadataJSON": {
      "default": "{\"123456551830\":\"us-east-1,us-east-2\"}",

This is the input which i have got as output of ssm step. where in both input and out has been attached. 

Can you please help in fixing the issue where it seems to be Metadatajson value is not proplery formatted. 

"{\"MetadataJSON\":\"{\"123456551830\":\"us-east-1,us-east-2\"}\",\"ProductName\":\"gami-v1\",\"ProductOSAndVersion\":\"Redhat-7.7\",\"version\":\"1\",\"AmiIDParamName\":\"/GoldenAMI/Redhat-7.7/gami-v1/1\", \"MetadataParamName\":\"/GoldenAMI/Redhat-7.7/gami-v1/1/temp\"}"


Below is the error Im getting, as like meta datajson is not formatted properly

Automation Step Execution fails when it is invoking the lambda function. Get Exception from Invoke API of lambda Service. Exception Message from Invoke API: [Could not parse request body into json: Unexpected character ('5' (code 53)): was expecting comma to separate Object entries at [Source: (byte[])"{"MetadataJSON":"{"123456551830":"us-east-1,us-east-2"}","ProductName":"gami-v1","ProductOSAndVersion":"Redhat-7.7","version":"1","AmiIDParamName":"/GoldenAMI/Redhat-7.7/gami-v1/1", "MetadataParamName":"/GoldenAMI/Redhat-7.7/gami-v1/1/temp"}"; line: 1, column: 21] (Service: AWSLambda; Status Code: 400; Error Code: InvalidRequestContentException; Request ID: 922e7ef8-c2c3-4f61-89a3-87d948b77fb7)]. Please refer to Automation Service Troubleshooting Guide for more diagnosis details.
