### ISSUE TITLE
json <> yaml

### ISSUE THREAD

**Issue by vincentvdk** [aws-samples/aws-golden-ami-pipeline-sample#5]
Hi,
Is there a reason that the Cloudformation templates are in JSON format? Are they being build by some tool?
Since Cloudformation supports Yaml input it would make the templates a lot more readable imo.
Would it be an option to also provide Yaml formatted templates?

**Comment by kwwaikar** [comment]
Hi Vincent, 
Thank you for your feedback. Currently, CloudFormation templates are currently available in JSON format only. However, we will consider your feedback in the future.

Here is how I use cloudformation designer for converting JSON templates into YAML format:
1. Open https://console.aws.amazon.com/cloudformation/designer/home?region=us-east-1 
2. Choose **template** tab from bottom left panel
3. Replace contents of the **new.template** textarea with contents of the cloudFormation template you are trying to convert into YAML.
4. Change “Choose template language:” from JSON to **YAML**.
5. This converts the JSON template into YAML format.

Until we do start providing YAML formatted files I hope the above solution helps you.
