### ISSUE TITLE
json formatting issues: Gold-AMi-Stack-CFT-CI.json

### ISSUE THREAD

**Issue by FallenHoot** [aws-samples/aws-golden-ami-pipeline-sample#6]
Few issues within Gold-AMi-Stack-CFT-CI.json It has a few misplaced `,`
Row: 514 Col: 34 - Bad string (Remove the `,`)
Row: 1907 Col: 24 - Bad string (Remove the `,`)
Row: 2456 Col: 43 - Unexpected ']' (Remove the `,`)
Row: 2488 Col: 138 - Unexpected ']' (Remove the `,`)
Row: 2792 Col: 21 - Unexpected ']' (Remove the `,`)

**Comment by kwwaikar** [comment]
Thanks for sharing this information. We have incorporated the fix.
