### ISSUE TITLE
SSM Parameters

### ISSUE THREAD

**Issue by getjaleel** [aws-samples/aws-golden-ami-pipeline-sample#8]
The Cloudformation Template Gold-AMi-Stack-CFT-CI.json can have SSM parameter creation section automatically. I have tried and tested the component that could further automate the creations of the required stack components.

**Comment by getjaleel** [comment]
"ssmParameterName": {
      "Type": "AWS::SSM::Parameter::Name<String>",
      "Default":"/GoldenAMI/latest",
      "Description": "Enter the Parameter value as path of your choince."


 "SSMParameters": {
      "Type": "AWS::SSM::Parameter",
      "Properties": {
        "Name": {"Ref":"ssmParameterName"},
        "Type":"String",
        "Value":"Enter AMI-ID of your choice",
        "Description":"Change the AMI value to your desired AMI of your choice for building Golden AMI"
      }
    },

**Comment by kwaikar** [comment]
Thank you for sharing this information. We will run regression tests and incorporate it in the next version.

**Comment by kwwaikar** [comment]
Thank you so much for sharing this information. We will run regression tests and incorporate it in the next version.
